server:
  port: 9090

app:
  database:
    schema-name: "demo"
  aggregation-completion:
    lock-duration-minutes: 1
    post-iteration-delay-ms: 5000
    cron-expression: "* 0 * * * *"
  kafka:
    topic-in: "test-in"
    topic-out: "test-out"
    topic-link: "test-link-out"
    topic-trigger: "test-trigger"

spring:
  datasource:
    name: "dataSource"
    generate-unique-name: false
    url: "jdbc:postgresql://localhost:5432/camel_demo"
    username: "postgres"
    password: "postgres"
  application:
    name: "camel-demo"

camel:
  health:
    enabled: true
  component:
    kafka:
      brokers: "localhost:9094"
      group-id: "camel-demo"
  springboot:
    main-run-controller: true