server:
  port: 9090

app:
  lockExpireMillis: 60000
  kafka:
    topic-in: "test-in"
    topic-out: "test-out"
    topic-link: "test-link-out"
    topic-trigger: "test-trigger"

spring:
  datasource:
    name: "dataSource"
    generate-unique-name: false
    url: "jdbc:postgresql://localhost:5432/camel_demo"
    username: "postgres"
    password: "postgres"
  application:
    name: "camel-demo"

camel:
  component:
    kafka:
      brokers: "localhost:9094"
      group-id: "camel-demo"
  springboot:
    main-run-controller: true